# Generated by Django 4.0.5 on 2022-06-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
