# Generated by Django 4.0.5 on 2022-06-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnews', '0003_alter_headline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='replies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='headline',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
