# Generated by Django 4.0.5 on 2022-06-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnews', '0005_remove_headline_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='image',
        ),
        migrations.AddField(
            model_name='headline',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
